### PR TITLE
Added logs before os.Exit(1) in main.go

### PR DESCRIPTION
**Pull request by akaitux**
#### Overview
Added logs before os.Exit(1) with error in main.go

#### What this PR does / why we need it
If you use the operator as is and do not add the /global-hooks directory to the image, the code exits with exit code 1 without any error messages.

### CODE REVIEW

**Review by nabokihms — APPROVED** [review]
Thank you for your contribution!

**Comment by diafour** [comment]
Oops you've broken JSON logging =) `fmt.Printf` should be replaced with `log.Error`.

**Comment by akaitux** [comment]
@diafour Sorry, I specifically made an issue so that someone from the team would add these changes, since I don’t know the entire infrastructure. Should I make another pr or will you fix it yourself?

**Comment by nabokihms** [comment]
This is not a problem, because this is the first error.

**Pull request merged**
